export const CESIUM_CONFIG = {
  ACCESS_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI5ZmExMzZkNC1hMGI2LTQ0ZTUtYTA2OS1lMTRkYWFlYTAyZWUiLCJpZCI6MzEyNjQzLCJpYXQiOjE3NTAwNzUyNDB9.-9M-9Wqg-IH2FBXb12RsWEMBXSFTOvKOISePRAZsSy8'
};

export const ANIMATION_CONFIG = {
  MAX_FRAMES_CACHE: 2,
  POLLING_INTERVAL: 2000,
  ANIMATION_DURATION: 4000,
  TRANSITION_DURATION: 1500, // 增加到1.5秒，提供更好的视觉体验
  PRELOAD_DELAY: 500,
  INTERPOLATION_STEPS: 40,
  FRAME_INTERVAL: 16
};

export const SIMULATION_CONFIG = {
  MAX_TIME_FRAME: 360,  // 支持更多帧数，将在运行时根据文件夹动态调整
  OLD_FOLDER_MAX_FRAMES: 6,
  NEW_FOLDER_MAX_FRAMES: 360
};

export const CACHE_CONFIG = {
  MAX_NETWORK_CACHE: 50,  // 增加网络数据缓存，支持更多帧
  MAX_SERVICE_CACHE: 50   // 增加服务数据缓存，支持更多帧
};

export const ENTITY_TYPES = {
  SATELLITE: 'satellite',
  STATION: 'station',
  ROADM: 'roadm'
};