export const CESIUM_CONFIG = {
  ACCESS_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI5ZmExMzZkNC1hMGI2LTQ0ZTUtYTA2OS1lMTRkYWFlYTAyZWUiLCJpZCI6MzEyNjQzLCJpYXQiOjE3NTAwNzUyNDB9.-9M-9Wqg-IH2FBXb12RsWEMBXSFTOvKOISePRAZsSy8'
};

export const ANIMATION_CONFIG = {
  MAX_FRAMES_CACHE: 2,
  POLLING_INTERVAL: 2000,
  ANIMATION_DURATION: 4000,
  TRANSITION_DURATION: 10000,
  PRELOAD_DELAY: 500,
  INTERPOLATION_STEPS: 40,
  FRAME_INTERVAL: 16
};

export const SIMULATION_CONFIG = {
  MAX_TIME_FRAME: 6
};

export const CACHE_CONFIG = {
  MAX_NETWORK_CACHE: 2,
  MAX_SERVICE_CACHE: 2
};

export const ENTITY_TYPES = {
  SATELLITE: 'satellite',
  STATION: 'station',
  ROADM: 'roadm'
};